services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    #restart: always
    healthcheck:
      #contains password
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=pipeline_ui
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=pipeline
      #contains password
      - MYSQL_PASSWORD=pipeline123
    expose:
      - 3306
  app:
    build: ./
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    #restart: always
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    environment:
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
networks:
  backnet:
  frontnet:
