version: "3.8"
services:
  app:
    build: ./
    command: python main.py run -h 0.0.0.0
    links:
      - db
    volumes:
      - ./code:/usr/src/code
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb/
