services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    #restart: always
    healthcheck:
      #contains password
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=pipeline_ui
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=pipeline
      #contains password
      - MYSQL_PASSWORD=pipeline123
    expose:
      - "32000:3306"
  app:
    build: ./
    command: flask run --host 0.0.0.0
    #restart: always
    ports:
      - 5000:5000
      - 8080:8080
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  proxy:
    build: proxy
    #restart: always
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - frontnet
volumes:
  db-data:
networks:
  backnet:
  frontnet:
